// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class InsuranceQuoteTestsTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void InsuranceQuote_Age25_Exp3_Acdnt0_Quote2500()
    {
        //Arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(850, 736);
       
        //Act
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Amey");
        driver.FindElement(By.Id("lastName")).SendKeys("Annamma");
        driver.FindElement(By.Id("address")).SendKeys("3555 Fountain ");
        driver.FindElement(By.Id("city")).SendKeys("Toronto");
        driver.FindElement(By.Id("postalCode")).SendKeys("L5M 7E8");
        driver.FindElement(By.Id("phone")).SendKeys("456-789-8952");
        driver.FindElement(By.Id("email")).SendKeys("amey@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
       
        //Assert
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$2500"));
        }
    }
    [Test]
    public void InsuranceQuote_InvalidEmail_ValidationError()
    {
        //Arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(816, 716);

        //Act
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rohan");
        driver.FindElement(By.Id("lastName")).SendKeys("George");
        driver.FindElement(By.Id("address")).SendKeys("8 Hickory Street");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("L7Y 7R8");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("897-789-7895");
        driver.FindElement(By.Id("email")).SendKeys("rohangmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("30");
        driver.FindElement(By.Id("experience")).SendKeys("2");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();

        //Assert
        Assert.That(driver.FindElement(By.Id("email-error")).Text, Is.EqualTo("Must be a valid email address"));
    }
    [Test]
    public void InsuranceQuote_InvalidPhone_ValidationError()
    {
        //Arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(812, 712);


        //Act
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.CssSelector(".card:nth-child(1) > div > .form-group:nth-child(1)")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Amey");
        driver.FindElement(By.Id("lastName")).SendKeys("Abraham");
        driver.FindElement(By.Id("address")).SendKeys("3555 Fountain");
        driver.FindElement(By.Id("city")).SendKeys("Mississaugua");
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("L5M 7E8");
        driver.FindElement(By.Id("phone")).SendKeys("789789455");
        driver.FindElement(By.Id("email")).SendKeys("amey@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).SendKeys("5");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }

        //Assert
        Assert.That(driver.FindElement(By.Id("phone-error")).Text, Is.EqualTo("Phone Number must follow the patterns 111-111-1111 or (111)111-1111"));
    }
    [Test]
    public void InsuranceQuote_InvalidPostalCode_ValidationError()
    {
        //Arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(820, 720);

        //Act
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Amey");
        driver.FindElement(By.Id("lastName")).SendKeys("Annamma");
        driver.FindElement(By.Id("address")).SendKeys("4555 Fountain Street");
        driver.FindElement(By.Id("city")).SendKeys("Toronto");
        driver.FindElement(By.Id("postalCode")).SendKeys("56M 76R");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("787-789-8520");
        driver.FindElement(By.Id("email")).SendKeys("ameyannamma@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("34");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("9");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();

        //Assert
        Assert.That(driver.FindElement(By.Id("postalCode-error")).Text, Is.EqualTo("Postal Code must follow the pattern A1A 1A1"));
    }
    [Test]
    public void InsuranceQuote_OmitAccidents_ValidationError()
    {
        //Arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(828, 728);

        //Act
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Abraham");
        driver.FindElement(By.Id("lastName")).SendKeys("A");
        driver.FindElement(By.Id("address")).SendKeys("3991 Chicory");
        driver.FindElement(By.Id("city")).SendKeys("Mississauga");
        driver.FindElement(By.Id("postalCode")).SendKeys("L3M 8E5");
        driver.FindElement(By.CssSelector(".col-md-4:nth-child(1)")).Click();
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("785-852-8888");
        driver.FindElement(By.Id("email")).SendKeys("abrahama@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("37");
        driver.FindElement(By.Id("experience")).SendKeys("10");
        driver.FindElement(By.Id("btnSubmit")).Click();

        //Assert
        Assert.That(driver.FindElement(By.Id("accidents-error")).Text, Is.EqualTo("Number of accidents is required"));
    }
    [Test]
    public void InsuranceQuote_OmitAddress_ValidationError()
    {
        //Arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(846, 736);

        //Act
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rohan T");
        driver.FindElement(By.Id("lastName")).SendKeys("George");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("L5T 1J5");
        driver.FindElement(By.Id("phone")).SendKeys("555-666-4444");
        driver.FindElement(By.Id("email")).SendKeys("rohantg@yahoo.com");
        driver.FindElement(By.Id("age")).SendKeys("27");
        driver.FindElement(By.Id("experience")).SendKeys("0");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();

        //Assert
        Assert.That(driver.FindElement(By.Id("address-error")).Text, Is.EqualTo("Address is required"));
    }
    [Test]
    public void InsuranceQuote_OmitAge_ValidationError()
    {
        //Arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(824, 724);

        //Act
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rohan");
        driver.FindElement(By.Id("lastName")).SendKeys("G");
        driver.FindElement(By.Id("address")).SendKeys("7 Hickory ");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("L7Y 8R8");
        driver.FindElement(By.Id("phone")).SendKeys("789-778-7777");
        driver.FindElement(By.Id("email")).SendKeys("rohang@gmail.com");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("10");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("2");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }

        //Assert
        Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Age (>=16) is required"));
    }
    [Test]
    public void InsuranceQuote_OmitExperience_ValidationError()
    {
        //Arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(832, 732);
       
        //Act
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("George");
        driver.FindElement(By.Id("lastName")).SendKeys("R");
        driver.FindElement(By.Id("address")).SendKeys("9 Seaside ");
        driver.FindElement(By.Id("city")).SendKeys("Toronto");
        driver.FindElement(By.Id("postalCode")).SendKeys("L0Y 3F1");
        driver.FindElement(By.Id("phone")).SendKeys("789-789-7896");
        driver.FindElement(By.Id("email")).SendKeys("georgeg@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("55");
        driver.FindElement(By.Id("accidents")).SendKeys("1");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }

        //Assert
        Assert.That(driver.FindElement(By.Id("experience-error")).Text, Is.EqualTo("Years of experience is required"));
    }
    [Test]
    public void InsuranceQuote_OmitName_ValidationError()
    {
        //Arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(838, 736);

        //Act
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Y");
        driver.FindElement(By.Id("address")).SendKeys("6 Queensbridge Drive");
        driver.FindElement(By.Id("city")).SendKeys("Mississaugua");
        driver.FindElement(By.Id("postalCode")).SendKeys("L5M 7S4");
        driver.FindElement(By.Id("phone")).SendKeys("258-963-4565");
        driver.FindElement(By.Id("email")).SendKeys("yhand@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("33");
        driver.FindElement(By.Id("experience")).SendKeys("7");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }

        //Assert
        Assert.That(driver.FindElement(By.Id("firstName-error")).Text, Is.EqualTo("First Name is required"));
    }
    [Test]
    public void InsuranceQuote_Age16_Exp0_Acdnt0_Quote4000()
    {
        //Arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(836, 736);

        //Act
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Amey");
        driver.FindElement(By.Id("lastName")).SendKeys("A");
        driver.FindElement(By.Id("address")).SendKeys("6574 Gallosbridge");
        driver.FindElement(By.Id("city")).SendKeys("Brampton");
        driver.FindElement(By.Id("phone")).SendKeys("222-564-8666");
        driver.FindElement(By.Id("email")).SendKeys("aamey@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("16");
        driver.FindElement(By.Id("experience")).SendKeys("0");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("postalCode")).SendKeys("L6I 4F1");
        driver.FindElement(By.Id("btnSubmit")).Click();

        //Assert
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$4000"));
        }
    }
    [Test]
    public void InsuranceQuote_OmitCity_ValidationError()
    {
        //Arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(850, 736);

        //Act
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Amey");
        driver.FindElement(By.Id("lastName")).SendKeys("Abraham");
        driver.FindElement(By.Id("address")).SendKeys("34 Deer Run");
        driver.FindElement(By.Id("postalCode")).SendKeys("L6Y 7G1");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("245-777-8888");
        driver.FindElement(By.Id("email")).SendKeys("ameyabraaham@yahoo.com");
        driver.FindElement(By.Id("age")).SendKeys("32");
        driver.FindElement(By.Id("experience")).SendKeys("9");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }

        //Assert
        Assert.That(driver.FindElement(By.Id("city-error")).Text, Is.EqualTo("City is required"));
    }
    [Test]
    public void InsuranceQuote_Age25_Exp3_Acdnt4_NoInsurance()
    {
        //Arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(811, 711);

        //Act
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rohan");
        driver.FindElement(By.Id("lastName")).SendKeys("George");
        driver.FindElement(By.Id("address")).SendKeys("8 Hickory");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("L6N 8R9");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("345-789-1111");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("rohan@yahoo.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("4");
        driver.FindElement(By.Id("btnSubmit")).Click();

        //Assert
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
        }
    }
    [Test]
    public void InsuranceQuote_Age29_Exp10_Acdnt1_Quote1800()
    {
        //Arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(836, 736);

        //Act
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rohan");
        driver.FindElement(By.Id("lastName")).SendKeys("T");
        driver.FindElement(By.Id("address")).SendKeys("6 Library Road");
        driver.FindElement(By.Id("city")).SendKeys("Scarborough");
        driver.FindElement(By.Id("postalCode")).SendKeys("L4M 6Y4");
        driver.FindElement(By.Id("phone")).SendKeys("233-789-8523");
        driver.FindElement(By.Id("email")).SendKeys("trohan@hotmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("29");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("10");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("1");
        driver.FindElement(By.Id("btnSubmit")).Click();

        //Assert
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$1800"));
        }
    }
    [Test]
    public void InsuranceQuote_Age35_Exp10_Acdnt2_Quote1350()
    {
        //Arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(808, 708);

        //Act
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Rohan");
        driver.FindElement(By.Id("lastName")).SendKeys("George");
        driver.FindElement(By.Id("address")).SendKeys("8 Hickory Street");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("L7Y 8R6");
        driver.FindElement(By.Id("phone")).SendKeys("789-852-7894");
        driver.FindElement(By.Id("email")).SendKeys("rohangeorge@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("experience")).SendKeys("10");
        driver.FindElement(By.Id("accidents")).SendKeys("2");
        driver.FindElement(By.Id("btnSubmit")).Click();

        //Assert
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$1350"));
        }
    }
    [Test]
    public void InsuranceQuote_ExperienceNegative1_ValidationError()
    {
        //Arrange
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(842, 736);

        //Act
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Amey");
        driver.FindElement(By.Id("lastName")).SendKeys("P");
        driver.FindElement(By.Id("address")).SendKeys("65 Webb Drive");
        driver.FindElement(By.Id("city")).SendKeys("Toronto");
        driver.FindElement(By.Id("postalCode")).SendKeys("O7M 7Q1");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("789-888-8523");
        driver.FindElement(By.Id("email")).SendKeys("amey@conestogac.on");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("30");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("-1");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("2");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }

        //Assert
        Assert.That(driver.FindElement(By.Id("experience-error")).Text, Is.EqualTo("Please enter a value greater than or equal to 0."));
    }
}
